server:
  port: 8999
  tomcat:
      uri-encoding: utf-8
  servlet:
    context-path: "/wf"
spring:
#  profiles:
    #激活开发环境
#    active: dev
  servlet:
    multipart:
      max-file-size: 1MB

  datasource:
    name: activiti
    url: jdbc:mysql://10.4.1.204:3306/activiti?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20

  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
    open-in-view: true
    generate-ddl: false
  liquibase:
      enabled: true
      change-log: classpath:activiti6/activiti-app-db-changelog.xml
  freemarker:
    check-template-location: false
  activiti:
    check-process-definitions: false
    # 启动activiti engine时检查并更新数据库，不存在则创建表，存在则跳过
    database-schema-update: "true"
  aop:
    proxy-target-class: false
logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug
# 暴露 actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# activiti6 临时文件存放处
contentstorage:
 fs:
  rootFolder: "data/"
  createRoot: true
  depth: 4
  blockSize: 1024






